# Generated by Django 3.2.16 on 2023-01-28 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20230128_0634'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='products_category',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
    ]
