# Generated by Django 3.2.16 on 2023-02-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20230205_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'PROCESSING'), ('PAID', 'PAID'), ('SHIPPED', 'SHIPPED'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED'), ('DRAFT', 'DRAFT')], default='DEAFT', max_length=255),
            preserve_default=False,
        ),
    ]
