# Generated by Django 3.2.16 on 2023-02-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_orderitem_orders_item_order_i_f64f26_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='orderitem',
            name='orders_item_order_i_f64f26_idx',
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'product', 'is_active'], name='orders_item_order_i_64611d_idx'),
        ),
    ]
