# Generated by Django 3.2.16 on 2023-02-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20230208_2253'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='orderitem',
            name='orders_item_order_i_64611d_idx',
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order_id', 'product_id', 'is_active'], name='orders_item_order_i_64611d_idx'),
        ),
    ]
